---
title: "Project 1"
author: "Gianni Spiga"
date: '2023-02-17'
output: html_document
---

# Data Description and Cleaning

```{r}
# Libraries 
library(knitr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(plotly)
library(MASS)
library(xtable) # For latex table
```
```{r}
# Loading in the data, we will use day.csv since it includes hour of the day 
bike <- read.csv("day.csv")
bike

# cnt is a linear combination of causual and registered bikes, so we will drop causual anf registered columns and use count. We will also drop instant, which is just an index column

# Temperature and Feeling temperature (temp and atemp) are nearly perfectly correlated, so we will drop column atemp
cor(bike$temp, bike$atemp)

# Error with select() when both dplyr and MASS libraries are loaded in,  
# https://www.statology.org/dplyr-error-in-select-unused-arguments/
bike.cor <- cor(bike %>% dplyr::select(-c(instant, dteday)))

#bike.cor <- cor(bike[,-1:-2])

# We make a correaltion heat map
bike.cor <- melt(bike.cor)

ggplotly(ggplot(bike.cor, aes(x = Var1,
                  y = Var2,
                  fill = value))+geom_tile() +  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))


# turn columns season, year, weekday, workingday, weathersit into factors
cols <- c("season", "yr", "mnth", "holiday","weekday", "workingday", "weathersit")
bike[cols] <- lapply(bike[cols], factor)
bike

# Working day is going to be linearly dependent on holiday and weekday, so we will remove it as well

#  Reduced bike 
bike.r <-
  dplyr::select(bike, -c("instant","dteday", "atemp", "casual", "registered", "workingday")) %>% na.omit()

# No NA values present in the data
bike.r

# Explore the dataset types
str(bike.r)

# declaring n
n <- nrow(bike.r)
```

````{r}
### Tables
# Season - should be very close
table(bike.r$season)

# Month - shoul also be very close
table(bike.r$mnth)

# Holiday
table(bike.r$holiday)

# We do not have heavy rain present in the data
table(bike.r$weathersit)



1#cor(dplyr::select(bike, -1))

### Visualizations
# Histograms
ggplotly(
  ggplot(bike.r, aes(x = cnt)) + geom_histogram(bins = 20, fill = "firebrick") + labs(x = "Count of Registered and Casual Bicycles", y = "Quantity Recorded", title = "Histogram of Total Users")
)


ggplotly(ggplot(bike, aes(x = cnt, fill = season)) + geom_histogram(
  bins = 25,
  alpha = 0.8,
  position = "identity"
) + labs(x = "Count of Registered and Casual Bicycles", y = "Quantity Recorded" , title = "Histogram of Total Users Seperated by Season"))

# Boxplots
ggplot(bike, aes(x = cnt, y = weekday, fill = yr)) + geom_boxplot() + scale_y_discrete(labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")) + labs(x = "Count of Registered and Casual Bicycles", y = "Day of the Week", fill = "Year") + scale_fill_discrete(labels=c("2011", "2012"))

# Check medians for interpretation 
bike.r %>% group_by(yr, weekday) %>% summarise(med = median(cnt))

ggplot(bike, aes(x = season, y = cnt, fill = season)) + geom_boxplot()+ labs(
    x = "Count of Registered and Casual Bicycles",
    y = "Normalized Temperature in Celsius" ,
    title = "Normalized Temperature vs. Bikes Rented Colored by Weather Conditions",
    fill = "Season"
  )

# Scatter plots
ggplotly(
  ggplot(bike, aes(
    x = cnt, y = temp, color = season
  )) + geom_point() + labs(x = "Count of Registered and Casual Bicycles", y = "Normalized Temperature in Celsius" , title = "Normalized Temperature vs. Bikes Rented Each Day Colored by Season")
)

ggplotly(
  ggplot(bike, aes(
    x = cnt, y = temp, color = weathersit
  )) + geom_point() + labs(
    x = "Count of Registered and Casual Bicycles",
    y = "Normalized Temperature in Celsius" ,
    title = "Normalized Temperature vs. Bikes Rented Colored by Weather Conditions",
    color = "Weather Condition"
  )
)

ggplot(data = bike.r, aes(x = weekday, y = cnt, fill = weekday)) + geom_boxplot()

# We do not have heavy rain present in the data
table(bike.r$weathersit)

# for working day
table(bike.r$workingday)

model <- glm(cnt ~ ., data = bike.r, family = poisson())
summary(model)


# Checking for overdispersion 
sigma2 <- model$deviance/(nrow(bike.r)-length(coef(model)))
sigma2

# Very large overdispersion 
```

```{r}
# Building a negative binomial model 
?glm.nb

nb.model<- glm.nb(cnt ~ ., data = bike.r)

# The dispersion is much better 
nb.model$deviance / (nrow(bike.r)-length(coef(nb.model)))

summary(nb.model)

# Stepwise regression, using BIC since we are focused on finding the true model rather than looking to predict
### THIS IS ONLY BACKWARDS SINCE NO SCOPE IS DEFINED
stepAIC(nb.model, trace = TRUE, k = log(n))

# WE CAN GO FORWARD AND BACKWARD WHEN DEFINING A SCOPE
Scope = list(upper = ~ season + yr + mnth + holiday + weekday + weathersit + temp + 
    hum + windspeed, lower = ~1)
stepAIC(nb.model, trace = TRUE, scope = Scope, k = log(n))

# These both pick the same model, so we will build a new glm with these predictors
nb.mod.step <- glm.nb(cnt ~ season + yr + holiday + weathersit + temp + 
    hum + windspeed, data = bike.r)
summary(nb.mod.step)

# Dispersion is even closer to 1
nb.mod.step$deviance / (n-length(coef(nb.mod.step)))


# Searching for model with interactions 
int.model <- glm.nb(cnt ~ (season + yr + holiday + weathersit + temp +hum + windspeed)^2, data = bike.r)
int.model.step <- stepAIC(int.model, trace = F, k = log(n))
summary(int.model.step)

int.model$deviance / (n-length(coef(int.model)))


# weathersit3 non signficant, making new dataframe where weathersit is encoded as 1 for clear and 2 for other
bike.enc <- bike.r %>% mutate(weathersit = replace(weathersit, weathersit != "1","2"))
#bike.enc

# Build a reduced model now with the new encoded weathersit
int.model.red <-
  glm.nb(
    cnt ~ season + yr + holiday + weathersit + temp + hum + windspeed + season:temp + yr:temp + weathersit:hum + weathersit:windspeed,
    data = bike.enc
  )
summary(int.model.red)

# Final stepwise regression with reduced interaction model and new encoding
newScope <- list(upper = ~ season + yr + holiday + weathersit + temp + hum + windspeed + season:temp + yr:temp + weathersit:hum + weathersit:windspeed, lower = ~1)
int.model.redstep <- stepAIC(int.model.red, scope = newScope, trace = T, k = log(n), direction = 'both') 
summary(int.model.redstep)

# Final Model with summary
final.model <- int.model.redstep
sumFin <- summary(final.model)

# Creating 95% CI for coefficients
coefCI <- cbind(sumFin$coef[,1], sumFin$coef[,1] - 1.96*sumFin$coef[,2], sumFin$coef[,1] + 1.96*sumFin$coef[,2])
colnames(coefCI) <- c("Coefficient", "95% CI Lower", "95% CI Upper")

#xtable(coefCI)
```
# Sensitivity Analysis
```{r}
# Runs test is going to show pattern based on order, we should reorder data for model, create a new shuffled data set and rebuild models to test residuals 
# using dplyr 
bike.shuffle <- dplyr::slice(bike.enc, sample(1:n()))

# Rebuild model based on shuffled data
run.mod.main <- glm.nb(cnt ~ season + yr + holiday + weathersit + temp + 
    hum + windspeed, data = bike.shuffle)
#summary(run.mod.main)
run.mod.int <- glm.nb(cnt ~ season + yr + holiday + weathersit + temp + hum + windspeed + season:temp + yr:temp + weathersit:hum + weathersit:windspeed, data = bike.shuffle)
summary(run.mod.int)

library(ggformula)
### Residual Analysis
res.P.main = residuals(run.mod.main, type="pearson")
res.D.main = residuals(run.mod.main, type="deviance") #or residuals(fit), by default
boxplot(cbind(res.P.main, res.D.main), names = c("Pearson", "Deviance"))

# Residuals for interaction model
res.P.int = residuals(run.mod.int, type="pearson")
res.D.int = residuals(run.mod.int, type="deviance") #or residuals(fit), by default
boxplot(cbind(res.P.int, res.D.int), names = c("Pearson", "Deviance"))

boxplot(nb.mod.step$residuals)
 
# Plot Deviance against fitted values 
# Main
# main.spline <- smooth.spline(nb.mod.step$fitted.values, res.D.main, spar=0.9)
# m.spl.dat <- data.frame(main.spline$yin, )
ggplotly(
  ggplot() + aes(x = run.mod.main$fitted.values, y = res.D.main) + geom_point() + stat_spline(spar = 0.5, size = 0.8, color = "firebrick") + labs(x = "Fitted Values", y = "Deviance Residuals", title = "Deviances Residuals vs Fitted Values for Model with Interactions")
)

# Interactions
ggplotly(
  ggplot() + aes(x = run.mod.int$fitted.values, y = res.D.int) + geom_point() + stat_spline(spar = 0.8, size = 0.8, color = "firebrick") + labs(x = "Fitted Values", y = "Deviance Residuals", title = "Deviances Residuals vs Fitted Values for Model with Interactions")
)

# The interaction model is a much better fit where as the main effects
# We will confirm with Runs test
library(lawstat)

runs.test(y = res.D.main, plot.it = T)

runs.test(y = res.D.int, plot.it = T)

# Outliers
png(file="cooks.png")
plot(final.model, which = 4)
dev.off()

png(file="leverage.png")
plot(final.model, which = 5)
dev.off()

plot(final.model, which = 4)
# Observing high leverage points
#xtable(bike.enc[c(65, 668, 725),])

# Check medians for interpretation 
bike.enc %>% group_by(yr, mnth) %>% summarise(med = median(cnt), meanHum = mean(hum))


bike.enc.red <- (bike.enc[-c(65, 668, 725),])
final.model.red <- glm.nb(cnt~ season + yr + holiday + weathersit + temp + hum + windspeed + season:temp + yr:temp + weathersit:hum + weathersit:windspeed, data = bike.enc.red)
sumFin
summary(final.model.red)

res.D.int.red = residuals(final.model.red, type="deviance")

# Check fit a final time 
ggplotly(
  ggplot() + aes(x = final.model.red$fitted.values, y = res.D.int.red) + geom_point() + stat_spline(size = 0.8, color = "firebrick") + labs(x = "Fitted Values", y = "Deviance Residuals", title = "Deviances Residuals vs Fitted Values for Model with Interactions with Removed Outliers")
)

runs.test(y = res.D.int.red, plot.it = T)
```

## Test for regression effect (LRT)

$$
H_0: \beta_{10} = \ldots = \beta_{15} = 0 \\ 
H_a: \beta_{10} \neq \ldots \neq \beta_{15} \neq 0
$$

```{r}
# Comparing reduced model with interactions to main effects only model
nb.mod.step <- glm.nb(cnt ~ season + yr + holiday + weathersit + temp + 
    hum + windspeed, data = bike.enc)
summary(nb.mod.step)

anova(nb.mod.step, final.model)



# Testing for overall regression effect (PG 44 of notes)
h0.fit = glm.nb(cnt~1,
             data = bike.r)
h0.fit
anova(h0.fit, nb.mod.step, test="Chi")

# We reject H_0

# Lets compare our stepwise with our full model 
anova(nb.model, nb.mod.step, test = "Chi")

anova(nb.mod.step,nb.model, test = "Chi")
```